# Site settings
title: Bork.
email: andrew.boorde@infielddigital.com
name: Andrew Boorde
description: > # this means to ignore newlines until "baseurl:"
  Front end blog documenting my journey through the wonderful 
  world of the web
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andrewboorde.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: pygments
lsi: false
sass:
   sass_dir: _sass
   style: compressed

# Profile links on the left sidebar, leave blank to ignore
social:
  github: andrewboorde
  bitbucket: andrewboorde 
  #twitter: bork
  #facebook: bork
  linkedin: aboorde
  gravatar: 1bc22e8b8accf3339f5f7dd2c4c9ba5f